sripujithaadavi/UF-Events

frontend/angular.json, frontend/package-lock.json, frontend/package.json, frontend/src/app/app.module.ts, frontend/src/index.html, frontend/src/styles.scss
=> setting up angular materials

frontend/src/app/app.component.html, frontend/src/app/app.component.scss, frontend/src/app/app.component.ts, frontend/src/app/app.module.ts, frontend/src/app/event-list/event-list.component.html, frontend/src/app/event-list/event-list.component.scss, frontend/src/app/event-list/event-list.component.spec.ts, frontend/src/app/event-list/event-list.component.ts
=> event list

frontend/src/app/app.module.ts, frontend/src/app/event-list/event-list.component.ts, frontend/src/app/event/event.component.html, frontend/src/app/event/event.component.scss, frontend/src/app/event/event.component.ts, frontend/src/app/types/event.interface.ts
=> adding upvoting feature

BACKEND/go.mod, BACKEND/home.go
=> 14 settingup go

BACKEND/home.go
=> event model added

frontend/src/app/app.component.html, frontend/src/app/app.module.ts, frontend/src/app/form/form.component.html, frontend/src/app/form/form.component.scss, frontend/src/app/form/form.component.spec.ts, frontend/src/app/form/form.component.ts
=> form creation

frontend/src/app/app.component.html, frontend/src/app/app.module.ts, frontend/src/app/event-list/event-list.component.ts, frontend/src/app/events.service.spec.ts, frontend/src/app/events.service.ts, frontend/src/app/form/form.component.html
=> integrating API to fetch list

frontend/src/app/event/event.component.html, frontend/src/app/events.service.ts, frontend/src/app/form/form.component.html, frontend/src/app/form/form.component.ts
=> integrating post API

frontend/cypress/fixtures/example.json, frontend/cypress/integration/1-getting-started/createTest.spec.js, frontend/cypress/plugins/index.js, frontend/cypress/support/commands.js, frontend/cypress/support/index.js
#31 re-commiting changes for cypress setup which got deleted by mistake
=> code for cypress setup

frontend/src/app/http.service.spec.ts, frontend/src/app/http.service.ts, frontend/src/app/register/register.component.html
=> http interceptor

frontend/src/app/event-detail/event-detail.component.html, frontend/src/app/event-detail/event-detail.component.spec.ts, frontend/src/app/event-detail/event-detail.component.ts
=> eventdetails

frontend/src/app/app-routing.module.ts
=> updating routing

frontend/src/app/app.module.ts
=> App module enhancement

frontend/src/app/event-list/event-list.component.ts
=> Adding navigation

frontend/src/app/events.service.ts
=> authentication

frontend/src/app/event/event.component.scss, frontend/src/app/events.service.ts, frontend/src/app/types/event.interface.ts
=> Fixing css issues

frontend/src/app/event-detail/event-detail.component.html, frontend/src/app/event-detail/event-detail.component.scss, frontend/src/app/event-detail/event-detail.component.ts, frontend/src/app/event-list/event-list.component.ts, frontend/src/app/signin/signin.component.ts
=> Integrating Api event details

frontend/cypress/integration/1-getting-started/createTest.spec.js
=> cypresstestccasesforregister

frontend/cypress/integration/1-getting-started/createTest.spec.js
=> 'signinandeventsformtestcases

frontend/cypress/integration/1-getting-started/createTest.spec.js
=> additional testcases for create event form

frontend/cypress/integration/1-getting-started/createTest.spec.js
=> testcasesforsigninandeventdisplay'

frontend/cypress/integration/1-getting-started/createTest.spec.js
=> testcasesforcreateformmultipleevents

frontend/src/app/filter/filter.component.html, frontend/src/app/filter/filter.component.scss, frontend/src/app/filter/filter.component.spec.ts, frontend/src/app/filter/filter.component.ts
=> Developing filter

frontend/src/app/event-list/event-list.component.html, frontend/src/app/event-list/event-list.component.ts, frontend/src/app/events.service.ts
=> Linking Filters

frontend/src/app/app.component.html, frontend/src/app/app.module.ts
=> Linking headers

frontend/src/app/form/form.component.html
=> Fixing form component

frontend/src/app/signin/signin.component.ts
=> Fixing issue in signin

frontend/src/app/filter/filter.component.ts
=> Updating Filters

frontend/src/app/event-list/event-list.component.html, frontend/src/app/event-list/event-list.component.ts
=> Updating list for filters

frontend/src/app/events.service.ts
=> User Functionality like or dislike

frontend/src/app/signin/signin.component.ts
=> Fixing issues in signin

frontend/src/app/register/register.component.html, frontend/src/app/register/register.component.ts
=> Fixing issues in register

frontend/cypress/integration/1-getting-started/createTest.spec.js
=> proper commenting for cypress test cases code

frontend/cypress/integration/1-getting-started/createTest.spec.js
=> Cypress test cases for filter format

frontend/cypress/integration/1-getting-started/createTest.spec.js
=> cypress test cases for filters

frontend/cypress/integration/1-getting-started/createTest.spec.js
=> Cypress testcases for filtering the event
